#!/bin/bash


AUDIO_IN=""; TEXT_IN=""; TEXT_OUT=""; CODEC_OUT=""; EMOTION_OUT=""
EVAL_AUDIO_IN=""; EVAL_TEXT_IN=""; EVAL_TEXT_OUT=""; EVAL_CODEC_OUT=""; EVAL_EMOTION_OUT=""
for i in "${!DATASET_DIRS[@]}"; do
	DDIR=${DATASET_DIRS[$i]}
	AUDIO_IN="$AUDIO_IN $DDIR/train.${AUDIO_IN_EXT[$i]}"
	EVAL_AUDIO_IN="$EVAL_AUDIO_IN $DDIR/eval.${AUDIO_IN_EXT[$i]}"
	TEXT_IN="$TEXT_IN $DDIR/train.${TEXT_IN_EXT[$i]}"
	EVAL_TEXT_IN="$EVAL_TEXT_IN $DDIR/eval.${TEXT_IN_EXT[$i]}"
	TEXT_OUT="$TEXT_OUT $DDIR/train.${TEXT_OUT_EXT[$i]}"
	EVAL_TEXT_OUT="$EVAL_TEXT_OUT $DDIR/eval.${TEXT_OUT_EXT[$i]}"
	EMOTION_OUT="$EMOTION_OUT $DDIR/train.${EMOTION_EXT[$i]}"
	EVAL_EMOTION_OUT="$EVAL_EMOTION_OUT $DDIR/eval.${EMOTION_EXT[$i]}"
	if [[ ${CODEC_OUT_EXT[$i]} == "<NONE>" ]]; then 
		CODEC_OUT="$CODEC_OUT <NONE>"
		EVAL_CODEC_OUT="$EVAL_CODEC_OUT <NONE>" 
	else 
		CODEC_OUT="$CODEC_OUT $DDIR/train.${CODEC_OUT_EXT[$i]}"
		EVAL_CODEC_OUT="$EVAL_CODEC_OUT $DDIR/eval.${CODEC_OUT_EXT[$i]}" 
	fi
done
